### ISSUE TITLE
"Disable" Easton Elementary Schools Toggle

### ISSUE THREAD

**Issue by greenec** [tanczosm/EASDAlert#1]
Toggle on if any elementary schools are selected, but do not make it an optional checkbox.

Alternatively, don't display the toggle at all and add "easd_elem" to the array of tags used in Azure hub registration if the user selects any of the elementary schools.

**Comment by tanczosm** [comment]
Good idea.   I dont want to make this a specific case for elementary schools so I think if you select a tag that extends any other existing tag then those parent tags should immediately be selected. That includes easd even though it's checked by default

**Comment by greenec** [comment]
We can add an integer field for ParentId to the Tag model, with 0 values being top level tags.

We can make EASD top-most and have multiple levels of child tags from there. 

Thoughts?

**Comment by tanczosm** [comment]
No worries.. I can just use the slug.

easd
easd_elem
easd_elem_shawnee

**Comment by greenec** [comment]
Split on underscores and build the hierarchies from there... sounds good.

Do you want that to happen at the API level? Or app level?

**Comment by greenec** [comment]
If you want to write the logic, I'll implement it in the API.

**Comment by tanczosm** [comment]
app level is fine

**Comment by tanczosm** [comment]
This issue is now implemented and 2 way binding is functional - works great

**Comment by greenec** [comment]
Resolved in which commit, exactly?

**Comment by tanczosm** [comment]
Here:  97cfa4cb5144d4fab04babcc8d6036155670dc97

**Comment by tanczosm** [comment]
Okay to close?

**Comment by greenec** [comment]
This is acceptable to me.
